Repository Cantera/cantera, pull requests merged in 2023-07, with the labels that each got.

#1518 Improve doxygen documentation of composite objects
  include/cantera/base/Interface.h
  include/cantera/base/Solution.h
  include/cantera/base/SolutionArray.h
Labels: documentation

#1524 Add support for building MATLAB toolbox on Apple Silicon
  src/matlab/SConscript
Labels: Matlab, macOS, compiling

#1529 [SCons] Require minimum HighFive version
  SConstruct
Labels: compiling

#1542 [SCons] Add deprecation warning for icc compiler
  SConstruct
Labels: compiling

#1545 Fix reading arrays containing subnormal floating point values
  src/base/AnyMap.cpp
  test/general/test_containers.cpp
Labels: Input

#1552 Fix serialization of phases with reactions from multiple YAML sections
  src/base/Solution.cpp
Labels: Input

#1553 [Kinetics] Implement band aid for plog validations
  src/kinetics/PlogRate.cpp
Labels: Input, Kinetics
