Repository Cantera/cantera, pull requests merged in 2023-04, with the labels that each got.

#1467 Add safeguards against Python 3.12
  SConstruct
  interfaces/cython/setup.cfg.in
  interfaces/python_minimal/setup.cfg.in
  interfaces/python_sdist/setup.cfg.in
Labels: compiling

#1463 Counterflow solution strategy
  interfaces/cython/cantera/_onedim.pyx
Labels: 1D Flames

#1479 [Equil] Handle factorization errors in initial estimator
  src/equil/ChemEquil.cpp
Labels: Equilibrium
