Repository Cantera/cantera, pull requests merged in 2023-08, with the labels that each got.

#1562 Update Doxygen style instructions
  CONTRIBUTING.md
Labels: documentation

#1571 Use C++17 attribute for deprecated types
  include/cantera/base/ct_defs.h
Labels: compiling

#1582 [docs] Make string entries more intuitive
  doc/sphinx/yaml/phases.rst
  doc/sphinx/yaml/reactions.rst
  doc/sphinx/yaml/species.rst
Labels: documentation

#1583 [docs] Clarify coverage-dependent surface species docs
  doc/sphinx/yaml/phases.rst
  doc/sphinx/yaml/species.rst
Labels: documentation

#1594 Fix issue #1593 in evaluating of lambda at boundary point.
  src/oneD/StFlow.cpp
Labels: 1D Flames

#1598 Add unit test for 1D constant lambda
  AUTHORS
  test/python/test_onedim.py
Labels: 1D Flames
