Repository Cantera/cantera, pull requests merged in 2024-11, with the labels that each got.

#1814 Fix use of kineticsSpeciesIndex in diamond_cvd examples
  samples/matlab_experimental/diamond_cvd.m
  samples/python/kinetics/diamond_cvd.py
Labels: Examples

#1813 Prevent two-point control from finding solutions with reverse flow
  src/oneD/Flow1D.cpp
Labels: 1D Flames

#1819 [thermo] Improve solveCubic exception handling
  src/thermo/MixtureFugacityTP.cpp
Labels: Thermo

#1820 Fix missing return code check in SConstruct script
  SConstruct
Labels: compiling
