Repository Cantera/cantera, pull requests merged in 2025-04, with the labels that each got.

#1866 [docs] Add link to 3.1 C++ documentation
  doc/doxygen/versions.md
Labels: documentation

#1876 Fix ck2yaml handling of unnamed surfaces
  interfaces/cython/cantera/ck2yaml.py
  test/data/surface2.inp
  test/python/test_convert.py
Labels: Input

#1858 Fix isotropic electron energy distribution expression
  include/cantera/thermo/PlasmaPhase.h
  src/thermo/PlasmaPhase.cpp
  test/python/test_thermo.py
Labels: Thermo
